import test from "node:test";
import assert from "node:assert";
import { access, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { PassThrough } from "node:stream";
import { compile } from "../src/compiler.js";
import { main } from "../src/cli.js";

function memoryStream() {
  return {
    text: "",
    write(chunk) {
      this.text += String(chunk);
    },
  };
}

function memoryIO() {
  return {
    stdout: memoryStream(),
    stderr: memoryStream(),
  };
}

function captureStream() {
  const stream = new PassThrough();
  stream.text = "";
  stream.on("data", (chunk) => {
    stream.text += String(chunk);
  });
  return stream;
}

async function withTempDir(t) {
  const dir = await mkdtemp(join(tmpdir(), "bnscript-cli-"));
  t.after(async () => {
    await rm(dir, { recursive: true, force: true });
  });
  return dir;
}

test("cli: compile success", () => {
  const result = compile(`dhori name = "BN"
dekhi name`, {
    filename: "success.bn",
  });

  assert.strictEqual(result.diagnostics.length, 0);
  assert.strictEqual(result.ast.type, "Program");
  assert.ok(result.js.includes("let name = \"BN\";"));
  assert.ok(result.js.includes("console.log(name);"));
});

test("cli: check success", async (t) => {
  const dir = await withTempDir(t);
  const filePath = join(dir, "check.bn");
  const io = memoryIO();

  await writeFile(
    filePath,
    `dhori name = "BN"
dekhi name`,
    "utf8"
  );

  const exitCode = await main(["check", filePath], io);

  assert.strictEqual(exitCode, 0);
  assert.ok(io.stdout.text.includes("BN Script check passed"));
  assert.strictEqual(io.stderr.text, "");
});

test("cli: build success", async (t) => {
  const dir = await withTempDir(t);
  const filePath = join(dir, "build.bn");
  const outputPath = join(dir, "build.js");
  const io = memoryIO();

  await writeFile(filePath, 'dekhi "hello"', "utf8");

  const exitCode = await main(["build", filePath], io);

  assert.strictEqual(exitCode, 0);
  assert.ok(io.stdout.text.includes(`Built ${outputPath}`));
  assert.strictEqual(await readFile(outputPath, "utf8"), `// Generated by BN Script Compiler v0.1
// Source: ${filePath}
// Do not edit this file directly.

console.log("hello");`);
});

test("cli: run success", async (t) => {
  const dir = await withTempDir(t);
  const filePath = join(dir, "run.bn");
  const io = memoryIO();
  const messages = [];
  const originalLog = console.log;

  t.after(() => {
    console.log = originalLog;
  });

  console.log = (...args) => {
    messages.push(args.join(" "));
  };

  await writeFile(filePath, 'dekhi "run works"', "utf8");

  const exitCode = await main(["run", filePath], io);

  assert.strictEqual(exitCode, 0);
  assert.deepStrictEqual(messages, ["run works"]);
  assert.strictEqual(io.stderr.text, "");
});

test("cli: file path shorthand runs like run command", async (t) => {
  const dir = await withTempDir(t);
  const filePath = join(dir, "shorthand.bn");
  const originalLog = console.log;

  async function runWithArgs(args) {
    const io = memoryIO();
    const messages = [];
    console.log = (...values) => {
      messages.push(values.join(" "));
    };

    const exitCode = await main(args, io);
    return {
      exitCode,
      messages,
      stderr: io.stderr.text,
      stdout: io.stdout.text,
    };
  }

  t.after(() => {
    console.log = originalLog;
  });

  await writeFile(filePath, 'dekhi "hello shorthand"', "utf8");

  const shorthand = await runWithArgs([filePath]);
  const explicit = await runWithArgs(["run", filePath]);

  assert.deepStrictEqual(shorthand, explicit);
  assert.strictEqual(shorthand.exitCode, 0);
  assert.deepStrictEqual(shorthand.messages, ["hello shorthand"]);
  assert.strictEqual(shorthand.stderr, "");
});

test("cli: repl exits cleanly", async () => {
  const input = new PassThrough();
  const io = {
    input,
    stdout: captureStream(),
    stderr: captureStream(),
  };
  input.end(".exit\n");

  const exitCode = await main(["repl"], io);

  assert.strictEqual(exitCode, 0);
  assert.ok(io.stdout.text.includes("BN Script REPL v0.1.0-alpha.0"));
  assert.ok(io.stdout.text.includes("Type .help for commands"));
  assert.strictEqual(io.stderr.text, "");
});

test("cli: run compile error", async (t) => {
  const dir = await withTempDir(t);
  const filePath = join(dir, "run-error.bn");
  const io = memoryIO();

  await writeFile(filePath, "dhori = 1", "utf8");

  const exitCode = await main(["run", filePath], io);

  assert.strictEqual(exitCode, 1);
  assert.ok(io.stderr.text.includes("ParseError"));
  assert.ok(io.stderr.text.includes("Expected variable name"));
});

test("cli: invalid command", async () => {
  const io = memoryIO();

  const exitCode = await main(["unknown", "program.bn"], io);

  assert.strictEqual(exitCode, 1);
  assert.strictEqual(io.stdout.text, "");
  assert.ok(io.stderr.text.includes("Usage:"));
});

test("cli: missing file", async (t) => {
  const dir = await withTempDir(t);
  const filePath = join(dir, "missing.bn");
  const io = memoryIO();

  const exitCode = await main(["check", filePath], io);

  assert.strictEqual(exitCode, 1);
  assert.strictEqual(io.stdout.text, "");
  assert.ok(io.stderr.text.includes("ENOENT"));
  assert.ok(io.stderr.text.includes(filePath));
});

test("cli: generated JS file exists", async (t) => {
  const dir = await withTempDir(t);
  const filePath = join(dir, "exists.bn");
  const outputPath = join(dir, "exists.js");
  const io = memoryIO();

  await writeFile(filePath, 'dekhi "exists"', "utf8");

  const exitCode = await main(["build", filePath], io);

  assert.strictEqual(exitCode, 0);
  await assert.doesNotReject(() => access(outputPath));
});

test("cli: compile error", () => {
  const result = compile("dhori = 1", {
    filename: "broken.bn",
  });

  assert.strictEqual(result.js, null);
  assert.ok(result.diagnostics.length > 0);
  assert.strictEqual(result.diagnostics[0].category, "ParseError");
  assert.ok(result.diagnostics[0].message.includes("Expected variable name"));
});

test("cli: semantic error", () => {
  const result = compile("dekhi missing", {
    filename: "semantic.bn",
  });

  assert.strictEqual(result.js, null);
  assert.ok(result.diagnostics.length > 0);
  assert.strictEqual(result.diagnostics[0].category, "SemanticError");
  assert.ok(result.diagnostics[0].message.includes("Use before declaration"));
});
