import test from "node:test";
import assert from "node:assert";
import { tokenize } from "../src/lexer.js";
import { parse } from "../src/parser.js";
import { analyze } from "../src/analyzer.js";
import { generate } from "../src/generator.js";

const HEADER = `// Generated by BN Script Compiler v0.1
// Source: test.bn
// Do not edit this file directly.`;

function compileSource(source) {
  const ast = parse(tokenize(source, "test.bn"), {
    filename: "test.bn",
    source,
  });
  analyze(ast, {
    filename: "test.bn",
    source,
  });
  return generate(ast);
}

function expected(body) {
  return `${HEADER}\n\n${body}`;
}

test("generator: declaration generation", () => {
  const output = compileSource(`dhori name = "Risat"
sthir age = 25`);

  assert.strictEqual(
    output,
    expected(`let name = "Risat";
const age = 25;`)
  );
});

test("generator: print generation", () => {
  const output = compileSource(`dhori name = "Risat"
dekhi name, "hello"`);

  assert.strictEqual(
    output,
    expected(`let name = "Risat";
console.log(name, "hello");`)
  );
});

test("generator: if generation", () => {
  const output = compileSource(`dhori ready = sotti
jodi ready {
  dekhi "yes"
} nahole {
  dekhi "no"
}`);

  assert.strictEqual(
    output,
    expected(`let ready = true;
if (ready) {
  console.log("yes");
} else {
  console.log("no");
}`)
  );
});

test("generator: nested blocks", () => {
  const output = compileSource(`{
  dhori x = 1
  {
    dekhi x
  }
}`);

  assert.strictEqual(
    output,
    expected(`{
  let x = 1;
  {
    console.log(x);
  }
}`)
  );
});

test("generator: binary operators", () => {
  const output = compileSource(`dhori a = 1
dhori b = 2
dhori calc = 1 + 2 * 3 - 4 / 2 % 2 ** 3
dhori same = a == b
dhori diff = a != b
dhori bigger = a >= b`);

  assert.strictEqual(
    output,
    expected(`let a = 1;
let b = 2;
let calc = 1 + 2 * 3 - 4 / 2 % 2 ** 3;
let same = a === b;
let diff = a !== b;
let bigger = a >= b;`)
  );
});

test("generator: logical operators", () => {
  const output = compileSource(`dhori a = sotti
dhori b = mittha
dhori ok = a ebong na b othoba b`);

  assert.strictEqual(
    output,
    expected(`let a = true;
let b = false;
let ok = a && !b || b;`)
  );
});

test("generator: unary operators", () => {
  const output = compileSource(`dhori negative = -5
dhori opposite = na sotti`);

  assert.strictEqual(
    output,
    expected(`let negative = -5;
let opposite = !true;`)
  );
});

test("generator: simple assignment output", () => {
  const output = compileSource(`dhori count = 0
count = count + 1`);

  assert.strictEqual(
    output,
    expected(`let count = 0;
count = count + 1;`)
  );
});

test("generator: compound assignment output", () => {
  const output = compileSource(`dhori count = 10
count += 5
count -= 2
count *= 3
count /= 2`);

  assert.strictEqual(
    output,
    expected(`let count = 10;
count += 5;
count -= 2;
count *= 3;
count /= 2;`)
  );
});

test("generator: complete assignment program", () => {
  const output = compileSource(`dhori count = 0
count = count + 1
count += 4
dekhi count`);

  assert.strictEqual(
    output,
    expected(`let count = 0;
count = count + 1;
count += 4;
console.log(count);`)
  );
});

test("generator: while loop output", () => {
  const output = compileSource(`dhori i = 0
jotokkhon i < 3 {
  dekhi i
}`);

  assert.strictEqual(
    output,
    expected(`let i = 0;
while (i < 3) {
  console.log(i);
}`)
  );
});

test("generator: complete while counter program", () => {
  const output = compileSource(`dhori i = 0

jotokkhon i < 3 {
  dekhi i
  i = i + 1
}`);

  assert.strictEqual(
    output,
    expected(`let i = 0;
while (i < 3) {
  console.log(i);
  i = i + 1;
}`)
  );
});

test("generator: array literal output", () => {
  const output = compileSource(`dhori names = ["Risat", "BN"]
dekhi names[0]`);

  assert.strictEqual(
    output,
    expected(`let names = ["Risat","BN"];
console.log(names[0]);`)
  );
});

test("generator: nested array output", () => {
  const output = compileSource(`dhori matrix = [[1], [2, 3]]
dekhi matrix[1][0]`);

  assert.strictEqual(
    output,
    expected(`let matrix = [[1],[2,3]];
console.log(matrix[1][0]);`)
  );
});

test("generator: object literal output", () => {
  const output = compileSource(`dhori user = {
  name: "Risat",
  age: 25
}
dekhi user.name`);

  assert.strictEqual(
    output,
    expected(`let user = { name: "Risat", age: 25 };
console.log(user.name);`)
  );
});

test("generator: nested object output", () => {
  const output = compileSource(`dhori user = {
  profile: {
    city: "Dhaka"
  }
}
dekhi user.profile.city`);

  assert.strictEqual(
    output,
    expected(`let user = { profile: { city: "Dhaka" } };
console.log(user.profile.city);`)
  );
});

test("generator: chained index and member access output", () => {
  const output = compileSource(`dhori users = [{ name: "Risat" }]
dekhi users[0].name`);

  assert.strictEqual(
    output,
    expected(`let users = [{ name: "Risat" }];
console.log(users[0].name);`)
  );
});

test("generator: assignment to member and index output", () => {
  const output = compileSource(`dhori user = { name: "Risat" }
dhori names = ["Risat"]
user.name = "Sayed"
names[0] = "Updated"`);

  assert.strictEqual(
    output,
    expected(`let user = { name: "Risat" };
let names = ["Risat"];
user.name = "Sayed";
names[0] = "Updated";`)
  );
});

test("generator: function declaration output", () => {
  const output = compileSource(`kaj greet(name) {
  dekhi name
}`);

  assert.strictEqual(
    output,
    expected(`function greet(name) {
  console.log(name);
}`)
  );
});

test("generator: return output", () => {
  const output = compileSource(`kaj identity(value) {
  ferot value
}`);

  assert.strictEqual(
    output,
    expected(`function identity(value) {
  return value;
}`)
  );
});

test("generator: function call output", () => {
  const output = compileSource(`kaj greet(name) {
  ferot name
}
dekhi greet("Risat")`);

  assert.strictEqual(
    output,
    expected(`function greet(name) {
  return name;
}
console.log(greet("Risat"));`)
  );
});

test("generator: complete function program", () => {
  const output = compileSource(`kaj greet(name) {
  ferot "Hello " + name
}

dekhi greet("Risat")`);

  assert.strictEqual(
    output,
    expected(`function greet(name) {
  return "Hello " + name;
}
console.log(greet("Risat"));`)
  );
});

test("generator: complete mini-program generation", () => {
  const output = compileSource(`sthir limit = 10
dhori count = 5
jodi count < limit ebong na mittha {
  dekhi "ok", count
}`);

  assert.strictEqual(
    output,
    expected(`const limit = 10;
let count = 5;
if (count < limit && !false) {
  console.log("ok", count);
}`)
  );
});
