import test from "node:test";
import assert from "node:assert";
import { tokenize } from "../src/lexer.js";
import { parse } from "../src/parser.js";
import { analyze } from "../src/analyzer.js";
import { generate } from "../src/generator.js";

const HEADER = `// Generated by BN Script Compiler v0.1
// Source: test.bn
// Do not edit this file directly.`;

function compileSource(source) {
  const ast = parse(tokenize(source, "test.bn"), {
    filename: "test.bn",
    source,
  });
  analyze(ast, {
    filename: "test.bn",
    source,
  });
  return generate(ast);
}

function expected(body) {
  return `${HEADER}\n\n${body}`;
}

test("generator: declaration generation", () => {
  const output = compileSource(`dhori name = "Risat"
sthir age = 25`);

  assert.strictEqual(
    output,
    expected(`let name = "Risat";
const age = 25;`)
  );
});

test("generator: import single output", () => {
  const output = compileSource('amdani { greet } theke "./utils.bn"');

  assert.strictEqual(
    output,
    expected('import { greet } from "./utils.js";')
  );
});

test("generator: import multiple output", () => {
  const output = compileSource(
    'amdani { greet, version } theke "./utils.bn"'
  );

  assert.strictEqual(
    output,
    expected('import { greet, version } from "./utils.js";')
  );
});

test("generator: runtime helper call output", () => {
  const output = compileSource(`dhori user = env("USER")

async kaj main() {
  dhori content = await fileRead("data.txt")
  await fileWrite("out.txt", content)
  await wait(1)
  dhori data = await httpGet("https://example.com")
  ferot data
}`);

  assert.strictEqual(
    output,
    expected(`import * as runtime from "./src/runtime/index.js";

let user = runtime.env("USER");
async function main() {
  let content = await runtime.fileRead("data.txt");
  await runtime.fileWrite("out.txt", content);
  await runtime.wait(1);
  let data = await runtime.httpGet("https://example.com");
  return data;
}`)
  );
});

test("generator: export function output", () => {
  const output = compileSource(`roptani kaj greet(name) {
  dekhi name
}`);

  assert.strictEqual(
    output,
    expected(`export function greet(name) {
  console.log(name);
}`)
  );
});

test("generator: export variable output", () => {
  const output = compileSource('roptani dhori version = "0.1"');

  assert.strictEqual(
    output,
    expected('export let version = "0.1";')
  );
});

test("generator: export const output", () => {
  const output = compileSource('roptani sthir APP = "BN"');

  assert.strictEqual(
    output,
    expected('export const APP = "BN";')
  );
});

test("generator: print generation", () => {
  const output = compileSource(`dhori name = "Risat"
dekhi name, "hello"`);

  assert.strictEqual(
    output,
    expected(`let name = "Risat";
console.log(name, "hello");`)
  );
});

test("generator: if generation", () => {
  const output = compileSource(`dhori ready = sotti
jodi ready {
  dekhi "yes"
} nahole {
  dekhi "no"
}`);

  assert.strictEqual(
    output,
    expected(`let ready = true;
if (ready) {
  console.log("yes");
} else {
  console.log("no");
}`)
  );
});

test("generator: nested blocks", () => {
  const output = compileSource(`{
  dhori x = 1
  {
    dekhi x
  }
}`);

  assert.strictEqual(
    output,
    expected(`{
  let x = 1;
  {
    console.log(x);
  }
}`)
  );
});

test("generator: binary operators", () => {
  const output = compileSource(`dhori a = 1
dhori b = 2
dhori calc = 1 + 2 * 3 - 4 / 2 % 2 ** 3
dhori same = a == b
dhori diff = a != b
dhori bigger = a >= b`);

  assert.strictEqual(
    output,
    expected(`let a = 1;
let b = 2;
let calc = 1 + 2 * 3 - 4 / 2 % 2 ** 3;
let same = a === b;
let diff = a !== b;
let bigger = a >= b;`)
  );
});

test("generator: logical operators", () => {
  const output = compileSource(`dhori a = sotti
dhori b = mittha
dhori ok = a ebong na b othoba b`);

  assert.strictEqual(
    output,
    expected(`let a = true;
let b = false;
let ok = a && !b || b;`)
  );
});

test("generator: unary operators", () => {
  const output = compileSource(`dhori negative = -5
dhori opposite = na sotti`);

  assert.strictEqual(
    output,
    expected(`let negative = -5;
let opposite = !true;`)
  );
});

test("generator: simple assignment output", () => {
  const output = compileSource(`dhori count = 0
count = count + 1`);

  assert.strictEqual(
    output,
    expected(`let count = 0;
count = count + 1;`)
  );
});

test("generator: compound assignment output", () => {
  const output = compileSource(`dhori count = 10
count += 5
count -= 2
count *= 3
count /= 2`);

  assert.strictEqual(
    output,
    expected(`let count = 10;
count += 5;
count -= 2;
count *= 3;
count /= 2;`)
  );
});

test("generator: complete assignment program", () => {
  const output = compileSource(`dhori count = 0
count = count + 1
count += 4
dekhi count`);

  assert.strictEqual(
    output,
    expected(`let count = 0;
count = count + 1;
count += 4;
console.log(count);`)
  );
});

test("generator: while loop output", () => {
  const output = compileSource(`dhori i = 0
jotokkhon i < 3 {
  dekhi i
}`);

  assert.strictEqual(
    output,
    expected(`let i = 0;
while (i < 3) {
  console.log(i);
}`)
  );
});

test("generator: complete while counter program", () => {
  const output = compileSource(`dhori i = 0

jotokkhon i < 3 {
  dekhi i
  i = i + 1
}`);

  assert.strictEqual(
    output,
    expected(`let i = 0;
while (i < 3) {
  console.log(i);
  i = i + 1;
}`)
  );
});

test("generator: range loop output", () => {
  const output = compileSource(`bar i = 0 theke 5 {
  dekhi i
}`);

  assert.strictEqual(
    output,
    expected(`for (let i = 0; i < 5; i++) {
  console.log(i);
}`)
  );
});

test("generator: foreach output", () => {
  const output = compileSource(`dhori names = ["Risat", "BN"]
bar item ekti names {
  dekhi item
}`);

  assert.strictEqual(
    output,
    expected(`let names = ["Risat","BN"];
for (const item of names) {
  console.log(item);
}`)
  );
});

test("generator: nested loops output", () => {
  const output = compileSource(`bar i = 0 theke 2 {
  bar j = 0 theke 2 {
    dekhi i
    dekhi j
  }
}`);

  assert.strictEqual(
    output,
    expected(`for (let i = 0; i < 2; i++) {
  for (let j = 0; j < 2; j++) {
    console.log(i);
    console.log(j);
  }
}`)
  );
});

test("generator: break and continue in while output", () => {
  const output = compileSource(`dhori i = 0
jotokkhon i < 5 {
  i = i + 1
  jodi i == 2 {
    cholo
  }
  jodi i == 4 {
    bekkhon
  }
  dekhi i
}`);

  assert.strictEqual(
    output,
    expected(`let i = 0;
while (i < 5) {
  i = i + 1;
  if (i === 2) {
    continue;
  }
  if (i === 4) {
    break;
  }
  console.log(i);
}`)
  );
});

test("generator: break and continue in range loop output", () => {
  const output = compileSource(`bar i = 0 theke 5 {
  jodi i == 2 {
    cholo
  }
  jodi i == 4 {
    bekkhon
  }
  dekhi i
}`);

  assert.strictEqual(
    output,
    expected(`for (let i = 0; i < 5; i++) {
  if (i === 2) {
    continue;
  }
  if (i === 4) {
    break;
  }
  console.log(i);
}`)
  );
});

test("generator: break and continue in foreach output", () => {
  const output = compileSource(`dhori names = ["Risat", "BN"]
bar item ekti names {
  jodi item == "BN" {
    bekkhon
  }
  cholo
}`);

  assert.strictEqual(
    output,
    expected(`let names = ["Risat","BN"];
for (const item of names) {
  if (item === "BN") {
    break;
  }
  continue;
}`)
  );
});

test("generator: array literal output", () => {
  const output = compileSource(`dhori names = ["Risat", "BN"]
dekhi names[0]`);

  assert.strictEqual(
    output,
    expected(`let names = ["Risat","BN"];
console.log(names[0]);`)
  );
});

test("generator: nested array output", () => {
  const output = compileSource(`dhori matrix = [[1], [2, 3]]
dekhi matrix[1][0]`);

  assert.strictEqual(
    output,
    expected(`let matrix = [[1],[2,3]];
console.log(matrix[1][0]);`)
  );
});

test("generator: object literal output", () => {
  const output = compileSource(`dhori user = {
  name: "Risat",
  age: 25
}
dekhi user.name`);

  assert.strictEqual(
    output,
    expected(`let user = { name: "Risat", age: 25 };
console.log(user.name);`)
  );
});

test("generator: nested object output", () => {
  const output = compileSource(`dhori user = {
  profile: {
    city: "Dhaka"
  }
}
dekhi user.profile.city`);

  assert.strictEqual(
    output,
    expected(`let user = { profile: { city: "Dhaka" } };
console.log(user.profile.city);`)
  );
});

test("generator: chained index and member access output", () => {
  const output = compileSource(`dhori users = [{ name: "Risat" }]
dekhi users[0].name`);

  assert.strictEqual(
    output,
    expected(`let users = [{ name: "Risat" }];
console.log(users[0].name);`)
  );
});

test("generator: assignment to member and index output", () => {
  const output = compileSource(`dhori user = { name: "Risat" }
dhori names = ["Risat"]
user.name = "Sayed"
names[0] = "Updated"`);

  assert.strictEqual(
    output,
    expected(`let user = { name: "Risat" };
let names = ["Risat"];
user.name = "Sayed";
names[0] = "Updated";`)
  );
});

test("generator: function declaration output", () => {
  const output = compileSource(`kaj greet(name) {
  dekhi name
}`);

  assert.strictEqual(
    output,
    expected(`function greet(name) {
  console.log(name);
}`)
  );
});

test("generator: async function output", () => {
  const output = compileSource(`async kaj fetchData() {
  ferot 123
}`);

  assert.strictEqual(
    output,
    expected(`async function fetchData() {
  return 123;
}`)
  );
});

test("generator: return output", () => {
  const output = compileSource(`kaj identity(value) {
  ferot value
}`);

  assert.strictEqual(
    output,
    expected(`function identity(value) {
  return value;
}`)
  );
});

test("generator: await output", () => {
  const output = compileSource(`kaj fetchData() {
  ferot 123
}

async kaj load() {
  dhori result = await fetchData()
}`);

  assert.strictEqual(
    output,
    expected(`function fetchData() {
  return 123;
}
async function load() {
  let result = await fetchData();
}`)
  );
});

test("generator: function call output", () => {
  const output = compileSource(`kaj greet(name) {
  ferot name
} 
dekhi greet("Risat")`);

  assert.strictEqual(
    output,
    expected(`function greet(name) {
  return name;
}
console.log(greet("Risat"));`)
  );
});

test("generator: async and await output", () => {
  const output = compileSource(`async kaj fetchData() {
  ferot "BN Script"
}

async kaj main() {
  ferot await fetchData()
}`);

  assert.strictEqual(
    output,
    expected(`async function fetchData() {
  return "BN Script";
}
async function main() {
  return await fetchData();
}`)
  );
});

test("generator: complete function program", () => {
  const output = compileSource(`kaj greet(name) {
  ferot "Hello " + name
}

dekhi greet("Risat")`);

  assert.strictEqual(
    output,
    expected(`function greet(name) {
  return "Hello " + name;
}
console.log(greet("Risat"));`)
  );
});

test("generator: complete mini-program generation", () => {
  const output = compileSource(`sthir limit = 10
dhori count = 5
jodi count < limit ebong na mittha {
  dekhi "ok", count
}`);

  assert.strictEqual(
    output,
    expected(`const limit = 10;
let count = 5;
if (count < limit && !false) {
  console.log("ok", count);
}`)
  );
});
