import test from "node:test";
import assert from "node:assert";
import * as AST from "../src/ast.js";
import { walkAST } from "../src/ast-walker.js";
import { analyze } from "../src/analyzer.js";
import { generate, Generator } from "../src/generator.js";
import { tokenize } from "../src/lexer.js";
import { parse } from "../src/parser.js";
import { containsTopLevelAwait } from "../src/repl.js";
import {
  RUNTIME_HELPER_NAMES,
  RUNTIME_HELPERS,
} from "../src/runtime/helpers.js";

const HEADER = `// Generated by BN Script Compiler v0.1
// Source: test.bn
// Do not edit this file directly.`;

function parseSource(source) {
  return parse(tokenize(source, "test.bn"), {
    filename: "test.bn",
    source,
  });
}

function compileSource(source) {
  const ast = parseSource(source);
  analyze(ast, {
    filename: "test.bn",
    source,
  });
  return generate(ast, {
    filename: "test.bn",
  });
}

function expected(body) {
  return `${HEADER}\n\n${body}`;
}

test("audit: ForLoop factory preserves range expressions and location metadata", () => {
  const start = AST.NumberLiteral(0, "0", {
    line: 1,
    column: 9,
    start: 8,
    end: 9,
  });
  const end = AST.NumberLiteral(5, "5", {
    line: 1,
    column: 17,
    start: 16,
    end: 17,
  });
  const body = AST.BlockStatement([], {
    line: 1,
    column: 19,
    start: 18,
    end: 20,
  });

  const loop = AST.ForLoop("i", start, end, body, {
    line: 1,
    column: 1,
    start: 0,
    end: 20,
  });

  assert.strictEqual(loop.type, "ForLoop");
  assert.strictEqual(loop.variant, "range");
  assert.strictEqual(loop.iterator, "i");
  assert.strictEqual(loop.start, start);
  assert.strictEqual(loop.end, end);
  assert.strictEqual(loop.body, body);
  assert.strictEqual(loop.line, 1);
  assert.strictEqual(loop.column, 1);
  assert.strictEqual(loop.locationStart, 0);
  assert.strictEqual(loop.locationEnd, 20);
});

test("audit: AST walker visits child AST nodes without primitive property keys", () => {
  const ast = parseSource(`dhori user = { name: "Risat" }
dekhi user.name`);
  const visited = [];

  walkAST(ast, (node) => {
    visited.push(node.type);
  });

  assert.ok(visited.includes("Program"));
  assert.ok(visited.includes("VarDeclaration"));
  assert.ok(visited.includes("ObjectLiteral"));
  assert.ok(visited.includes("StringLiteral"));
  assert.ok(visited.includes("PrintStatement"));
  assert.ok(visited.includes("MemberExpression"));
  assert.ok(visited.includes("Identifier"));
  assert.ok(!visited.includes("name"));
});

test("audit: runtime helper list is canonical for analyzer and generator paths", () => {
  assert.deepStrictEqual([...RUNTIME_HELPERS], RUNTIME_HELPER_NAMES);

  const source = 'dhori home = env("HOME")';
  const ast = parseSource(source);
  analyze(ast, {
    filename: "test.bn",
    source,
  });

  const generator = new Generator({
    filename: "test.bn",
  });

  assert.strictEqual(generator.usesRuntimeHelpers(ast), true);
  assert.ok(generate(ast, { filename: "test.bn" }).includes("runtime.env"));
});

test("audit: runtime helper detection uses walker across try blocks", () => {
  const source = `dhoro {
  await wait(1)
} sheshe {
  dekhi "done"
}`;
  const ast = parseSource(source);
  analyze(ast, {
    filename: "test.bn",
    source,
  });

  const generator = new Generator({
    filename: "test.bn",
  });

  assert.strictEqual(generator.usesRuntimeHelpers(ast), true);
});

test("audit: top-level await detection uses walker but skips function bodies", () => {
  const topLevel = parseSource("await wait(1)");
  const functionOnly = parseSource(`async kaj load() {
  await wait(1)
}`);

  assert.strictEqual(containsTopLevelAwait(topLevel.body[0]), true);
  assert.strictEqual(containsTopLevelAwait(functionOnly.body[0]), false);
});

test("audit: string interpolation emits a JavaScript template literal", () => {
  const output = compileSource('dhori name = "Risat"\ndekhi "Hello ${name}"');

  assert.strictEqual(
    output,
    expected('let name = "Risat";\nconsole.log(`Hello ${name}`);')
  );
});

test("audit: normal strings remain JSON string literals", () => {
  const output = compileSource('dekhi "Hello" + " plain"');

  assert.strictEqual(
    output,
    expected('console.log("Hello" + " plain");')
  );
});

test("audit: interpolated strings escape backticks", () => {
  const output = compileSource('dekhi "Hello `${name}"');

  assert.strictEqual(output, expected("console.log(`Hello \\`${name}`);"));
});
