const KEYWORDS = [
  {
    keyword: "dhori",
    title: "BN Script Variable Declaration",
    description_bn: "Notun mutable variable declare kore.",
    description_en: "Declares a mutable variable.",
  },
  {
    keyword: "let",
    title: "BN Script Variable Declaration",
    description_bn: "Notun mutable variable declare kore.",
    description_en: "Declares a mutable variable.",
  },
  {
    keyword: "sthir",
    title: "BN Script Constant Declaration",
    description_bn: "Notun constant declare kore.",
    description_en: "Declares an immutable constant.",
  },
  {
    keyword: "const",
    title: "BN Script Constant Declaration",
    description_bn: "Notun constant declare kore.",
    description_en: "Declares an immutable constant.",
  },
  {
    keyword: "dekhi",
    title: "BN Script Print",
    description_bn: "Console e value dekhe.",
    description_en: "Prints a value to the console.",
  },
  {
    keyword: "print",
    title: "BN Script Print",
    description_bn: "Console e value dekhe.",
    description_en: "Prints a value to the console.",
  },
  {
    keyword: "jodi",
    title: "BN Script Conditional",
    description_bn: "Condition true hole block run kore.",
    description_en: "Runs a block when a condition is true.",
  },
  {
    keyword: "if",
    title: "BN Script Conditional",
    description_bn: "Condition true hole block run kore.",
    description_en: "Runs a block when a condition is true.",
  },
  {
    keyword: "nahole",
    title: "BN Script Else Branch",
    description_bn: "Jodi condition false hoy tahole alternate block run kore.",
    description_en: "Runs an alternate block when the condition is false.",
  },
  {
    keyword: "else",
    title: "BN Script Else Branch",
    description_bn: "Jodi condition false hoy tahole alternate block run kore.",
    description_en: "Runs an alternate block when the condition is false.",
  },
  {
    keyword: "jotokkhon",
    title: "BN Script While Loop",
    description_bn: "Condition true thaka porjonto loop cholay.",
    description_en: "Runs a loop while a condition remains true.",
  },
  {
    keyword: "while",
    title: "BN Script While Loop",
    description_bn: "Condition true thaka porjonto loop cholay.",
    description_en: "Runs a loop while a condition remains true.",
  },
  {
    keyword: "bar",
    title: "BN Script Loop",
    description_bn: "Range ba for-each loop start kore.",
    description_en: "Starts a range or for-each loop.",
  },
  {
    keyword: "for",
    title: "BN Script Loop",
    description_bn: "Range ba for-each loop start kore.",
    description_en: "Starts a range or for-each loop.",
  },
  {
    keyword: "theke",
    title: "BN Script Range Loop Bound",
    description_bn: "Range loop er start theke end alada kore.",
    description_en: "Separates the start and end expressions in a range loop.",
  },
  {
    keyword: "from",
    title: "BN Script Import Source",
    description_bn: "Import source file bole.",
    description_en: "Introduces the source file in an import declaration.",
  },
  {
    keyword: "to",
    title: "BN Script Range Loop Bound",
    description_bn: "Range loop er end expression bole.",
    description_en: "Introduces the end expression in an English range loop.",
  },
  {
    keyword: "ekti",
    title: "BN Script For-Each Loop",
    description_bn: "Iterable er prottek item er jonno loop chalai.",
    description_en: "Introduces the iterable in a for-each loop.",
  },
  {
    keyword: "of",
    title: "BN Script For-Each Loop",
    description_bn: "Iterable er prottek item er jonno loop chalai.",
    description_en: "Introduces the iterable in a for-each loop.",
  },
  {
    keyword: "kaj",
    title: "BN Script Function",
    description_bn: "Function define kore.",
    description_en: "Defines a function.",
  },
  {
    keyword: "function",
    title: "BN Script Function",
    description_bn: "Function define kore.",
    description_en: "Defines a function.",
  },
  {
    keyword: "ferot",
    title: "BN Script Return",
    description_bn: "Function theke value ferot dey.",
    description_en: "Returns a value from a function.",
  },
  {
    keyword: "return",
    title: "BN Script Return",
    description_bn: "Function theke value ferot dey.",
    description_en: "Returns a value from a function.",
  },
  {
    keyword: "ebong",
    title: "BN Script Logical And",
    description_bn: "Duita condition true kina check kore.",
    description_en: "Checks whether both conditions are true.",
  },
  {
    keyword: "and",
    title: "BN Script Logical And",
    description_bn: "Duita condition true kina check kore.",
    description_en: "Checks whether both conditions are true.",
  },
  {
    keyword: "othoba",
    title: "BN Script Logical Or",
    description_bn: "Duita condition er moddhe konota true kina check kore.",
    description_en: "Checks whether either condition is true.",
  },
  {
    keyword: "or",
    title: "BN Script Logical Or",
    description_bn: "Duita condition er moddhe konota true kina check kore.",
    description_en: "Checks whether either condition is true.",
  },
  {
    keyword: "na",
    title: "BN Script Logical Not",
    description_bn: "Condition er value ulta kore.",
    description_en: "Negates a condition.",
  },
  {
    keyword: "not",
    title: "BN Script Logical Not",
    description_bn: "Condition er value ulta kore.",
    description_en: "Negates a condition.",
  },
  {
    keyword: "bekkhon",
    title: "BN Script Break",
    description_bn: "Loop bondho kore ber hoy.",
    description_en: "Exits the current loop.",
  },
  {
    keyword: "break",
    title: "BN Script Break",
    description_bn: "Loop bondho kore ber hoy.",
    description_en: "Exits the current loop.",
  },
  {
    keyword: "cholo",
    title: "BN Script Continue",
    description_bn: "Current loop iteration skip kore porer iteration e jai.",
    description_en: "Skips to the next loop iteration.",
  },
  {
    keyword: "continue",
    title: "BN Script Continue",
    description_bn: "Current loop iteration skip kore porer iteration e jai.",
    description_en: "Skips to the next loop iteration.",
  },
  {
    keyword: "amdani",
    title: "BN Script Import",
    description_bn: "Onno file theke naam import kore.",
    description_en: "Imports named values from another file.",
  },
  {
    keyword: "import",
    title: "BN Script Import",
    description_bn: "Onno file theke naam import kore.",
    description_en: "Imports named values from another file.",
  },
  {
    keyword: "roptani",
    title: "BN Script Export",
    description_bn: "Current file theke declaration export kore.",
    description_en: "Exports a declaration from the current file.",
  },
  {
    keyword: "export",
    title: "BN Script Export",
    description_bn: "Current file theke declaration export kore.",
    description_en: "Exports a declaration from the current file.",
  },
  {
    keyword: "dhoro",
    title: "BN Script Try",
    description_bn: "Error hote pare emon code block start kore.",
    description_en: "Starts a block that may throw an error.",
  },
  {
    keyword: "try",
    title: "BN Script Try",
    description_bn: "Error hote pare emon code block start kore.",
    description_en: "Starts a block that may throw an error.",
  },
  {
    keyword: "error",
    title: "BN Script Catch",
    description_bn: "Dhoro block er error handle kore.",
    description_en: "Handles an error from a try block.",
  },
  {
    keyword: "catch",
    title: "BN Script Catch",
    description_bn: "Dhoro block er error handle kore.",
    description_en: "Handles an error from a try block.",
  },
  {
    keyword: "sheshe",
    title: "BN Script Finally",
    description_bn: "Try/catch sesh hole always run kore.",
    description_en: "Runs after try/catch whether an error occurs or not.",
  },
  {
    keyword: "finally",
    title: "BN Script Finally",
    description_bn: "Try/catch sesh hole always run kore.",
    description_en: "Runs after try/catch whether an error occurs or not.",
  },
  {
    keyword: "async",
    title: "BN Script Async Function",
    description_bn: "Await use korte pare emon async function define kore.",
    description_en: "Defines an async function that can use await.",
  },
  {
    keyword: "await",
    title: "BN Script Await",
    description_bn: "Async operation-er jonno opekkha kore.",
    description_en: "Waits for an async operation.",
  },
  {
    keyword: "sotti",
    title: "BN Script Boolean True",
    description_bn: "True boolean value.",
    description_en: "Represents the true boolean value.",
  },
  {
    keyword: "true",
    title: "BN Script Boolean True",
    description_bn: "True boolean value.",
    description_en: "Represents the true boolean value.",
  },
  {
    keyword: "mittha",
    title: "BN Script Boolean False",
    description_bn: "False boolean value.",
    description_en: "Represents the false boolean value.",
  },
  {
    keyword: "false",
    title: "BN Script Boolean False",
    description_bn: "False boolean value.",
    description_en: "Represents the false boolean value.",
  },
  {
    keyword: "khali",
    title: "BN Script Null",
    description_bn: "Khali ba null value.",
    description_en: "Represents the null value.",
  },
  {
    keyword: "null",
    title: "BN Script Null",
    description_bn: "Khali ba null value.",
    description_en: "Represents the null value.",
  },
];

const KEYWORD_MAP = new Map(KEYWORDS.map((entry) => [entry.keyword, entry]));

function getKeyword(keyword) {
  return KEYWORD_MAP.get(keyword);
}

module.exports = {
  KEYWORDS,
  getKeyword,
};
