import { createError } from "./errors.js";

const BINARY_OPERATORS = new Map([
  ["othoba", { js: "||", precedence: 1, associativity: "left" }],
  ["ebong", { js: "&&", precedence: 2, associativity: "left" }],
  ["==", { js: "===", precedence: 3, associativity: "left" }],
  ["!=", { js: "!==", precedence: 3, associativity: "left" }],
  [">", { js: ">", precedence: 4, associativity: "left" }],
  ["<", { js: "<", precedence: 4, associativity: "left" }],
  [">=", { js: ">=", precedence: 4, associativity: "left" }],
  ["<=", { js: "<=", precedence: 4, associativity: "left" }],
  ["+", { js: "+", precedence: 5, associativity: "left" }],
  ["-", { js: "-", precedence: 5, associativity: "left" }],
  ["*", { js: "*", precedence: 6, associativity: "left" }],
  ["/", { js: "/", precedence: 6, associativity: "left" }],
  ["%", { js: "%", precedence: 6, associativity: "left" }],
  ["**", { js: "**", precedence: 7, associativity: "right" }],
]);

const UNARY_OPERATORS = new Map([
  ["na", "!"],
  ["-", "-"],
]);

const UNARY_PRECEDENCE = 8;

class Emitter {
  constructor() {
    this.lines = [];
    this.indentLevel = 0;
  }

  indent() {
    this.indentLevel += 1;
  }

  dedent() {
    this.indentLevel = Math.max(0, this.indentLevel - 1);
  }

  emitLine(text = "") {
    if (text === "") {
      this.lines.push("");
      return;
    }

    this.lines.push(`${"  ".repeat(this.indentLevel)}${text}`);
  }

  getOutput() {
    return this.lines.join("\n");
  }
}

export class Generator {
  constructor({ filename } = {}) {
    this.filename = filename;
    this.emitter = new Emitter();
  }

  generate(node) {
    if (node?.type === "Program") {
      return this.generateProgram(node);
    }

    this.emitStatement(node);
    return this.emitter.getOutput();
  }

  generateProgram(node) {
    const sourceFile = this.filename || node.sourceFile || "<anonymous>";
    this.emitter.emitLine("// Generated by BN Script Compiler v0.1");
    this.emitter.emitLine(`// Source: ${sourceFile}`);
    this.emitter.emitLine("// Do not edit this file directly.");
    this.emitter.emitLine();

    for (const statement of node.body) {
      this.emitStatement(statement);
    }

    return this.emitter.getOutput();
  }

  emitStatement(node) {
    switch (node?.type) {
      case "VarDeclaration":
        return this.emitDeclaration("let", node);
      case "ConstDeclaration":
        return this.emitDeclaration("const", node);
      case "PrintStatement":
        return this.emitPrintStatement(node);
      case "ExpressionStatement":
        return this.emitter.emitLine(`${this.generateExpression(node.expression)};`);
      case "IfStatement":
        return this.emitIfStatement(node);
      case "WhileStatement":
        return this.emitWhileStatement(node);
      case "BlockStatement":
      case "Block":
        return this.emitBlockStatement(node);
      case "FunctionDeclaration":
        return this.emitFunctionDeclaration(node);
      case "ReturnStatement":
        return this.emitReturnStatement(node);
      default:
        return this.unsupported(node);
    }
  }

  emitDeclaration(keyword, node) {
    this.emitter.emitLine(
      `${keyword} ${node.name} = ${this.generateExpression(node.initializer)};`
    );
  }

  emitPrintStatement(node) {
    const args = node.arguments.map((argument) => this.generateExpression(argument));
    this.emitter.emitLine(`console.log(${args.join(", ")});`);
  }

  emitIfStatement(node) {
    this.emitter.emitLine(`if (${this.generateExpression(node.condition)}) {`);
    this.emitBlockBody(node.consequent);

    for (const alternate of node.alternates || []) {
      this.emitter.emitLine(
        `} else if (${this.generateExpression(alternate.condition)}) {`
      );
      this.emitBlockBody(alternate.consequent);
    }

    if (node.elseBlock) {
      this.emitter.emitLine("} else {");
      this.emitBlockBody(node.elseBlock);
    }

    this.emitter.emitLine("}");
  }

  emitWhileStatement(node) {
    this.emitter.emitLine(`while (${this.generateExpression(node.condition)}) {`);
    this.emitBlockBody(node.body);
    this.emitter.emitLine("}");
  }

  emitBlockStatement(node) {
    this.emitter.emitLine("{");
    this.emitBlockBody(node);
    this.emitter.emitLine("}");
  }

  emitBlockBody(node) {
    this.emitter.indent();
    for (const statement of node.body || []) {
      this.emitStatement(statement);
    }
    this.emitter.dedent();
  }

  emitFunctionDeclaration(node) {
    const params = (node.params || []).map((param) =>
      typeof param === "string" ? param : param.name
    );
    this.emitter.emitLine(`function ${node.name}(${params.join(", ")}) {`);
    this.emitBlockBody(node.body);
    this.emitter.emitLine("}");
  }

  emitReturnStatement(node) {
    if (node.value) {
      this.emitter.emitLine(`return ${this.generateExpression(node.value)};`);
      return;
    }

    this.emitter.emitLine("return;");
  }

  generateExpression(node) {
    switch (node?.type) {
      case "Identifier":
        return node.name;
      case "NumberLiteral":
        return node.raw || String(node.value);
      case "StringLiteral":
        return JSON.stringify(node.value);
      case "BooleanLiteral":
        return node.value ? "true" : "false";
      case "NullLiteral":
        return "null";
      case "UnaryExpression":
        return this.generateUnaryExpression(node);
      case "BinaryExpression":
        return this.generateBinaryExpression(node);
      case "Assignment":
      case "AssignmentExpression":
        return this.generateAssignmentExpression(node);
      case "CallExpression":
        return this.generateCallExpression(node);
      default:
        return this.unsupported(node);
    }
  }

  generateAssignmentExpression(node) {
    return `${this.generateExpression(node.target)} ${node.operator} ${this.generateExpression(node.value)}`;
  }

  generateCallExpression(node) {
    const callee = this.formatCallCallee(node.callee);
    const args = (node.arguments || []).map((argument) =>
      this.generateExpression(argument)
    );
    return `${callee}(${args.join(", ")})`;
  }

  formatCallCallee(node) {
    const callee = this.generateExpression(node);

    if (node?.type === "Identifier" || node?.type === "CallExpression") {
      return callee;
    }

    return `(${callee})`;
  }

  generateUnaryExpression(node) {
    const operator = UNARY_OPERATORS.get(node.operator);
    if (!operator) {
      return this.unsupported(node);
    }

    const operand = this.formatUnaryOperand(node.operand);
    return `${operator}${operand}`;
  }

  formatUnaryOperand(node) {
    if (node?.type === "BinaryExpression") {
      return `(${this.generateExpression(node)})`;
    }

    if (node?.type === "AssignmentExpression" || node?.type === "Assignment") {
      return `(${this.generateExpression(node)})`;
    }

    if (node?.type === "UnaryExpression") {
      return `(${this.generateExpression(node)})`;
    }

    return this.generateExpression(node);
  }

  generateBinaryExpression(node) {
    const operator = BINARY_OPERATORS.get(node.operator);
    if (!operator) {
      return this.unsupported(node);
    }

    const left = this.formatBinaryChild(node.left, node, "left");
    const right = this.formatBinaryChild(node.right, node, "right");
    return `${left} ${operator.js} ${right}`;
  }

  formatBinaryChild(child, parent, side) {
    const childExpression = this.generateExpression(child);

    if (child?.type === "UnaryExpression") {
      return parent.operator === "**" && side === "left"
        ? `(${childExpression})`
        : childExpression;
    }

    if (child?.type === "AssignmentExpression" || child?.type === "Assignment") {
      return `(${childExpression})`;
    }

    if (child?.type !== "BinaryExpression") {
      return childExpression;
    }

    const childOperator = BINARY_OPERATORS.get(child.operator);
    const parentOperator = BINARY_OPERATORS.get(parent.operator);

    if (!childOperator || !parentOperator) {
      return childExpression;
    }

    if (childOperator.precedence < parentOperator.precedence) {
      return `(${childExpression})`;
    }

    if (childOperator.precedence > parentOperator.precedence) {
      return childExpression;
    }

    if (parentOperator.associativity === "right") {
      return side === "left" ? `(${childExpression})` : childExpression;
    }

    return side === "right" ? `(${childExpression})` : childExpression;
  }

  unsupported(node) {
    throw createError({
      category: "InternalError",
      message: `Generator does not support AST node "${node?.type || "<missing>"}".`,
      filename: this.filename || "<anonymous>",
      line: node?.line,
      column: node?.column,
      suggestion:
        "Limit Generator Stage 4 input to the supported parser subset or extend the generator for this node.",
    });
  }
}

export function generate(ast, options = {}) {
  return new Generator(options).generate(ast);
}
