import { createError } from "./errors.js";

const BINARY_OPERATORS = new Map([
  ["othoba", { js: "||", precedence: 1, associativity: "left" }],
  ["ebong", { js: "&&", precedence: 2, associativity: "left" }],
  ["==", { js: "===", precedence: 3, associativity: "left" }],
  ["!=", { js: "!==", precedence: 3, associativity: "left" }],
  [">", { js: ">", precedence: 4, associativity: "left" }],
  ["<", { js: "<", precedence: 4, associativity: "left" }],
  [">=", { js: ">=", precedence: 4, associativity: "left" }],
  ["<=", { js: "<=", precedence: 4, associativity: "left" }],
  ["+", { js: "+", precedence: 5, associativity: "left" }],
  ["-", { js: "-", precedence: 5, associativity: "left" }],
  ["*", { js: "*", precedence: 6, associativity: "left" }],
  ["/", { js: "/", precedence: 6, associativity: "left" }],
  ["%", { js: "%", precedence: 6, associativity: "left" }],
  ["**", { js: "**", precedence: 7, associativity: "right" }],
]);

const UNARY_OPERATORS = new Map([
  ["na", "!"],
  ["-", "-"],
]);

const UNARY_PRECEDENCE = 8;
const RUNTIME_HELPERS = new Set([
  "env",
  "fileRead",
  "fileWrite",
  "wait",
  "httpGet",
]);
const DEFAULT_RUNTIME_IMPORT = "./src/runtime/index.js";

class Emitter {
  constructor() {
    this.lines = [];
    this.indentLevel = 0;
  }

  indent() {
    this.indentLevel += 1;
  }

  dedent() {
    this.indentLevel = Math.max(0, this.indentLevel - 1);
  }

  emitLine(text = "") {
    if (text === "") {
      this.lines.push("");
      return;
    }

    this.lines.push(`${"  ".repeat(this.indentLevel)}${text}`);
  }

  getOutput() {
    return this.lines.join("\n");
  }
}

export class Generator {
  constructor({ filename, runtimeImport = null } = {}) {
    this.filename = filename;
    this.emitter = new Emitter();
    this.runtimeImport = runtimeImport;
  }

  generate(node) {
    if (node?.type === "Program") {
      return this.generateProgram(node);
    }

    this.emitStatement(node);
    return this.emitter.getOutput();
  }

  generateProgram(node) {
    const sourceFile = this.filename || node.sourceFile || "<anonymous>";
    const usesRuntime = this.usesRuntimeHelpers(node);
    this.emitter.emitLine("// Generated by BN Script Compiler v0.1");
    this.emitter.emitLine(`// Source: ${sourceFile}`);
    this.emitter.emitLine("// Do not edit this file directly.");
    this.emitter.emitLine();

    if (usesRuntime) {
      this.emitter.emitLine(
        `import * as runtime from ${JSON.stringify(this.runtimeImportSpecifier())};`
      );
      this.emitter.emitLine();
    }

    for (const statement of node.body) {
      this.emitStatement(statement);
    }

    return this.emitter.getOutput();
  }

  emitStatement(node) {
    switch (node?.type) {
      case "ImportDeclaration":
        return this.emitImportDeclaration(node);
      case "ExportDeclaration":
        return this.emitExportDeclaration(node);
      case "VarDeclaration":
        return this.emitDeclaration("let", node);
      case "ConstDeclaration":
        return this.emitDeclaration("const", node);
      case "PrintStatement":
        return this.emitPrintStatement(node);
      case "ExpressionStatement":
        return this.emitter.emitLine(`${this.generateExpression(node.expression)};`);
      case "IfStatement":
        return this.emitIfStatement(node);
      case "TryStatement":
        return this.emitTryStatement(node);
      case "WhileStatement":
        return this.emitWhileStatement(node);
      case "ForLoop":
        return this.emitForLoop(node);
      case "ForEachLoop":
        return this.emitForEachLoop(node);
      case "BlockStatement":
      case "Block":
        return this.emitBlockStatement(node);
      case "FunctionDeclaration":
        return this.emitFunctionDeclaration(node);
      case "ReturnStatement":
        return this.emitReturnStatement(node);
      case "BreakStatement":
        return this.emitBreakStatement();
      case "ContinueStatement":
        return this.emitContinueStatement();
      default:
        return this.unsupported(node);
    }
  }

  emitDeclaration(keyword, node) {
    this.emitter.emitLine(
      `${keyword} ${node.name} = ${this.generateExpression(node.initializer)};`
    );
  }

  runtimeImportSpecifier() {
    return this.runtimeImport || DEFAULT_RUNTIME_IMPORT;
  }

  emitImportDeclaration(node) {
    const imports = (node.imports || []).map((specifier) => specifier.name);
    const source = this.formatModuleSource(node.source?.value || "");
    this.emitter.emitLine(
      `import { ${imports.join(", ")} } from ${JSON.stringify(source)};`
    );
  }

  emitExportDeclaration(node) {
    const declaration = node.declaration;

    switch (declaration?.type) {
      case "FunctionDeclaration":
        return this.emitFunctionDeclaration(declaration, "export ");
      case "ConstDeclaration":
        return this.emitter.emitLine(
          `export const ${declaration.name} = ${this.generateExpression(declaration.initializer)};`
        );
      case "VarDeclaration":
        return this.emitter.emitLine(
          `export let ${declaration.name} = ${this.generateExpression(declaration.initializer)};`
        );
      default:
        return this.unsupported(node);
    }
  }

  formatModuleSource(source) {
    if (source.endsWith(".bn")) {
      return `${source.slice(0, -3)}.js`;
    }

    return source;
  }

  usesRuntimeHelpers(node) {
    switch (node?.type) {
      case "Program":
      case "BlockStatement":
      case "Block":
        return (node.body || []).some((statement) =>
          this.usesRuntimeHelpers(statement)
        );
      case "ImportDeclaration":
      case "BreakStatement":
      case "ContinueStatement":
      case "NumberLiteral":
      case "StringLiteral":
      case "BooleanLiteral":
      case "NullLiteral":
      case "Identifier":
        return false;
      case "ExportDeclaration":
        return this.usesRuntimeHelpers(node.declaration);
      case "VarDeclaration":
      case "ConstDeclaration":
        return this.usesRuntimeHelpers(node.initializer);
      case "PrintStatement":
        return (node.arguments || []).some((argument) =>
          this.usesRuntimeHelpers(argument)
        );
      case "ExpressionStatement":
        return this.usesRuntimeHelpers(node.expression);
      case "IfStatement":
        return (
          this.usesRuntimeHelpers(node.condition) ||
          this.usesRuntimeHelpers(node.consequent) ||
          (node.alternates || []).some(
            (alternate) =>
              this.usesRuntimeHelpers(alternate.condition) ||
              this.usesRuntimeHelpers(alternate.consequent)
          ) ||
          this.usesRuntimeHelpers(node.elseBlock)
        );
      case "TryStatement":
        return (
          this.usesRuntimeHelpers(node.tryBlock) ||
          this.usesRuntimeHelpers(node.catchBlock) ||
          this.usesRuntimeHelpers(node.finallyBlock)
        );
      case "WhileStatement":
        return (
          this.usesRuntimeHelpers(node.condition) ||
          this.usesRuntimeHelpers(node.body)
        );
      case "ForLoop":
        return (
          this.usesRuntimeHelpers(node.start) ||
          this.usesRuntimeHelpers(node.end) ||
          this.usesRuntimeHelpers(node.body)
        );
      case "ForEachLoop":
        return (
          this.usesRuntimeHelpers(node.iterable) ||
          this.usesRuntimeHelpers(node.body)
        );
      case "FunctionDeclaration":
        return this.usesRuntimeHelpers(node.body);
      case "ReturnStatement":
        return this.usesRuntimeHelpers(node.value);
      case "UnaryExpression":
        return this.usesRuntimeHelpers(node.operand);
      case "AwaitExpression":
        return this.usesRuntimeHelpers(node.argument);
      case "BinaryExpression":
        return (
          this.usesRuntimeHelpers(node.left) ||
          this.usesRuntimeHelpers(node.right)
        );
      case "AssignmentExpression":
      case "Assignment":
        return (
          this.usesRuntimeHelpers(node.target) ||
          this.usesRuntimeHelpers(node.value)
        );
      case "CallExpression":
        return (
          this.isRuntimeHelperCall(node) ||
          this.usesRuntimeHelpers(node.callee) ||
          (node.arguments || []).some((argument) =>
            this.usesRuntimeHelpers(argument)
          )
        );
      case "MemberExpression":
        return (
          this.usesRuntimeHelpers(node.object) ||
          (node.computed && this.usesRuntimeHelpers(node.property))
        );
      case "ArrayLiteral":
        return (node.elements || []).some((element) =>
          this.usesRuntimeHelpers(element)
        );
      case "ObjectLiteral":
        return (node.properties || []).some((property) =>
          this.usesRuntimeHelpers(property.value)
        );
      default:
        return false;
    }
  }

  isRuntimeHelperCall(node) {
    return (
      node?.type === "CallExpression" &&
      node.callee?.type === "Identifier" &&
      RUNTIME_HELPERS.has(node.callee.name)
    );
  }

  emitPrintStatement(node) {
    const args = node.arguments.map((argument) => this.generateExpression(argument));
    this.emitter.emitLine(`console.log(${args.join(", ")});`);
  }

  emitIfStatement(node) {
    this.emitter.emitLine(`if (${this.generateExpression(node.condition)}) {`);
    this.emitBlockBody(node.consequent);

    for (const alternate of node.alternates || []) {
      this.emitter.emitLine(
        `} else if (${this.generateExpression(alternate.condition)}) {`
      );
      this.emitBlockBody(alternate.consequent);
    }

    if (node.elseBlock) {
      this.emitter.emitLine("} else {");
      this.emitBlockBody(node.elseBlock);
    }

    this.emitter.emitLine("}");
  }

  emitTryStatement(node) {
    this.emitter.emitLine("try {");
    this.emitBlockBody(node.tryBlock);

    if (node.catchBlock) {
      this.emitter.emitLine(`} catch (${node.catchParam.name}) {`);
      this.emitBlockBody(node.catchBlock);
    }

    if (node.finallyBlock) {
      this.emitter.emitLine("} finally {");
      this.emitBlockBody(node.finallyBlock);
    }

    this.emitter.emitLine("}");
  }

  emitWhileStatement(node) {
    this.emitter.emitLine(`while (${this.generateExpression(node.condition)}) {`);
    this.emitBlockBody(node.body);
    this.emitter.emitLine("}");
  }

  emitForLoop(node) {
    if (node.variant !== "range") {
      return this.unsupported(node);
    }

    const start = this.generateExpression(node.start);
    const end = this.generateExpression(node.end);
    this.emitter.emitLine(
      `for (let ${node.iterator} = ${start}; ${node.iterator} < ${end}; ${node.iterator}++) {`
    );
    this.emitBlockBody(node.body);
    this.emitter.emitLine("}");
  }

  emitForEachLoop(node) {
    const iterable = this.generateExpression(node.iterable);
    this.emitter.emitLine(`for (const ${node.iterator} of ${iterable}) {`);
    this.emitBlockBody(node.body);
    this.emitter.emitLine("}");
  }

  emitBlockStatement(node) {
    this.emitter.emitLine("{");
    this.emitBlockBody(node);
    this.emitter.emitLine("}");
  }

  emitBlockBody(node) {
    this.emitter.indent();
    for (const statement of node.body || []) {
      this.emitStatement(statement);
    }
    this.emitter.dedent();
  }

  emitFunctionDeclaration(node, prefix = "") {
    const params = (node.params || []).map((param) =>
      typeof param === "string" ? param : param.name
    );
    const asyncPrefix = node.isAsync === true ? "async " : "";
    this.emitter.emitLine(
      `${prefix}${asyncPrefix}function ${node.name}(${params.join(", ")}) {`
    );
    this.emitBlockBody(node.body);
    this.emitter.emitLine("}");
  }

  emitReturnStatement(node) {
    if (node.value) {
      this.emitter.emitLine(`return ${this.generateExpression(node.value)};`);
      return;
    }

    this.emitter.emitLine("return;");
  }

  emitBreakStatement() {
    this.emitter.emitLine("break;");
  }

  emitContinueStatement() {
    this.emitter.emitLine("continue;");
  }

  generateExpression(node) {
    switch (node?.type) {
      case "Identifier":
        return node.name;
      case "NumberLiteral":
        return node.raw || String(node.value);
      case "StringLiteral":
        return JSON.stringify(node.value);
      case "BooleanLiteral":
        return node.value ? "true" : "false";
      case "NullLiteral":
        return "null";
      case "UnaryExpression":
        return this.generateUnaryExpression(node);
      case "AwaitExpression":
        return this.generateAwaitExpression(node);
      case "BinaryExpression":
        return this.generateBinaryExpression(node);
      case "Assignment":
      case "AssignmentExpression":
        return this.generateAssignmentExpression(node);
      case "CallExpression":
        return this.generateCallExpression(node);
      case "MemberExpression":
        return this.generateMemberExpression(node);
      case "ArrayLiteral":
        return this.generateArrayLiteral(node);
      case "ObjectLiteral":
        return this.generateObjectLiteral(node);
      default:
        return this.unsupported(node);
    }
  }

  generateAssignmentExpression(node) {
    return `${this.generateExpression(node.target)} ${node.operator} ${this.generateExpression(node.value)}`;
  }

  generateArrayLiteral(node) {
    return `[${(node.elements || [])
      .map((element) => this.generateExpression(element))
      .join(",")}]`;
  }

  generateObjectLiteral(node) {
    const properties = (node.properties || []).map((property) => {
      return `${this.formatObjectKey(property.key)}: ${this.generateExpression(property.value)}`;
    });
    return properties.length > 0 ? `{ ${properties.join(", ")} }` : "{}";
  }

  formatObjectKey(key) {
    return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key)
      ? key
      : JSON.stringify(key);
  }

  generateMemberExpression(node) {
    const object = this.formatMemberObject(node.object);

    if (node.computed) {
      return `${object}[${this.generateExpression(node.property)}]`;
    }

    return `${object}.${node.property}`;
  }

  formatMemberObject(node) {
    const object = this.generateExpression(node);

    if (
      node?.type === "Identifier" ||
      node?.type === "MemberExpression" ||
      node?.type === "CallExpression"
    ) {
      return object;
    }

    return `(${object})`;
  }

  generateCallExpression(node) {
    const callee = this.isRuntimeHelperCall(node)
      ? `runtime.${node.callee.name}`
      : this.formatCallCallee(node.callee);
    const args = (node.arguments || []).map((argument) =>
      this.generateExpression(argument)
    );
    return `${callee}(${args.join(", ")})`;
  }

  formatCallCallee(node) {
    const callee = this.generateExpression(node);

    if (
      node?.type === "Identifier" ||
      node?.type === "CallExpression" ||
      node?.type === "MemberExpression"
    ) {
      return callee;
    }

    return `(${callee})`;
  }

  generateUnaryExpression(node) {
    const operator = UNARY_OPERATORS.get(node.operator);
    if (!operator) {
      return this.unsupported(node);
    }

    const operand = this.formatUnaryOperand(node.operand);
    return `${operator}${operand}`;
  }

  generateAwaitExpression(node) {
    return `await ${this.formatAwaitArgument(node.argument)}`;
  }

  formatAwaitArgument(node) {
    if (node?.type === "BinaryExpression") {
      return `(${this.generateExpression(node)})`;
    }

    if (node?.type === "AssignmentExpression" || node?.type === "Assignment") {
      return `(${this.generateExpression(node)})`;
    }

    return this.generateExpression(node);
  }

  formatUnaryOperand(node) {
    if (node?.type === "BinaryExpression") {
      return `(${this.generateExpression(node)})`;
    }

    if (node?.type === "AssignmentExpression" || node?.type === "Assignment") {
      return `(${this.generateExpression(node)})`;
    }

    if (node?.type === "UnaryExpression") {
      return `(${this.generateExpression(node)})`;
    }

    return this.generateExpression(node);
  }

  generateBinaryExpression(node) {
    const operator = BINARY_OPERATORS.get(node.operator);
    if (!operator) {
      return this.unsupported(node);
    }

    const left = this.formatBinaryChild(node.left, node, "left");
    const right = this.formatBinaryChild(node.right, node, "right");
    return `${left} ${operator.js} ${right}`;
  }

  formatBinaryChild(child, parent, side) {
    const childExpression = this.generateExpression(child);

    if (child?.type === "UnaryExpression") {
      return parent.operator === "**" && side === "left"
        ? `(${childExpression})`
        : childExpression;
    }

    if (child?.type === "AssignmentExpression" || child?.type === "Assignment") {
      return `(${childExpression})`;
    }

    if (child?.type !== "BinaryExpression") {
      return childExpression;
    }

    const childOperator = BINARY_OPERATORS.get(child.operator);
    const parentOperator = BINARY_OPERATORS.get(parent.operator);

    if (!childOperator || !parentOperator) {
      return childExpression;
    }

    if (childOperator.precedence < parentOperator.precedence) {
      return `(${childExpression})`;
    }

    if (childOperator.precedence > parentOperator.precedence) {
      return childExpression;
    }

    if (parentOperator.associativity === "right") {
      return side === "left" ? `(${childExpression})` : childExpression;
    }

    return side === "right" ? `(${childExpression})` : childExpression;
  }

  unsupported(node) {
    throw createError({
      category: "InternalError",
      message: `Generator does not support AST node "${node?.type || "<missing>"}".`,
      filename: this.filename || "<anonymous>",
      line: node?.line,
      column: node?.column,
      suggestion:
        "Limit Generator Stage 4 input to the supported parser subset or extend the generator for this node.",
    });
  }
}

export function generate(ast, options = {}) {
  return new Generator(options).generate(ast);
}
