import { createInterface } from "node:readline/promises";
import { stdin, stdout, stderr } from "node:process";
import { Script, createContext } from "node:vm";
import { inspect } from "node:util";
import { walkAST } from "./ast-walker.js";
import { compile } from "./compiler.js";
import * as runtime from "./runtime/index.js";

export const VERSION = "0.1.0-alpha.0";
export const REPL_HELP = `.help   Show help
.exit   Exit REPL
.clear  Clear screen
.version Show version`;

const HEADER_LINES = [
  "// Generated by BN Script Compiler v0.1",
  "// Source:",
  "// Do not edit this file directly.",
];

function write(stream, text) {
  stream.write(text);
}

function formatConsoleValue(value) {
  if (typeof value === "string") {
    return value;
  }

  return inspect(value, {
    colors: false,
    depth: 4,
  });
}

function formatDiagnostic(error) {
  if (typeof error?.format === "function") {
    return error.format();
  }

  const category = error?.category || error?.name || "BNError";
  const message = error?.message || String(error);
  return `BNError:\n[${category}] ${message}`;
}

function stripGeneratedWrapper(js) {
  const lines = (js || "").split(/\r?\n/);
  const body = [];

  for (const line of lines) {
    if (HEADER_LINES.some((header) => line.startsWith(header))) {
      continue;
    }

    if (line.startsWith("import * as runtime from ")) {
      continue;
    }

    body.push(line);
  }

  return body.join("\n").trim();
}

function newExecutableChunk(previous, next) {
  if (!previous) {
    return next;
  }

  if (next === previous) {
    return "";
  }

  const prefix = `${previous}\n`;
  if (next.startsWith(prefix)) {
    return next.slice(prefix.length);
  }

  throw new Error("REPL execution state diverged from compiled session state.");
}

export function containsTopLevelAwait(node) {
  let found = false;

  walkAST(node, (current) => {
    if (current.type === "FunctionDeclaration") {
      return false;
    }

    if (current.type === "AwaitExpression") {
      found = true;
      return false;
    }

    return !found;
  });

  return found;
}

function prepareTopLevelAwaitChunk(chunk) {
  return chunk.replace(
    /^(let|const)\s+([A-Za-z_$][A-Za-z0-9_$]*)\s*=/gm,
    "globalThis.$2 ="
  );
}

async function runScriptChunk(chunk, context, filename, topLevelAwait) {
  const source = topLevelAwait
    ? `(async () => {\n${prepareTopLevelAwaitChunk(chunk)}\n})()`
    : chunk;
  const script = new Script(source, {
    filename,
  });
  const value = script.runInContext(context);
  if (value && typeof value.then === "function") {
    await value;
  }
}

export class ReplSession {
  constructor({
    io = { stdout, stderr },
    filename = "<repl>",
  } = {}) {
    this.io = io;
    this.filename = filename;
    this.source = "";
    this.executable = "";
    this.statementCount = 0;
    this.context = this.createExecutionContext();
  }

  createExecutionContext() {
    return createContext({
      console: {
        log: (...args) => {
          write(
            this.io.stdout,
            `${args.map((arg) => formatConsoleValue(arg)).join(" ")}\n`
          );
        },
      },
      runtime,
      setTimeout,
      clearTimeout,
      Promise,
    });
  }

  async handleLine(input) {
    const line = String(input ?? "");
    const command = line.trim();

    if (command === "") {
      return { exit: false };
    }

    if (command.startsWith(".")) {
      return this.handleCommand(command);
    }

    return await this.executeSource(line);
  }

  handleCommand(command) {
    switch (command) {
      case ".help":
        write(this.io.stdout, `${REPL_HELP}\n`);
        return { exit: false };
      case ".exit":
        return { exit: true };
      case ".clear":
        write(this.io.stdout, "\x1Bc");
        return { exit: false };
      case ".version":
        write(this.io.stdout, `${VERSION}\n`);
        return { exit: false };
      default:
        write(this.io.stderr, `Unknown REPL command: ${command}\n`);
        write(this.io.stderr, 'Type ".help" for commands.\n');
        return { exit: false };
    }
  }

  async executeSource(line) {
    const candidateSource = this.source ? `${this.source}\n${line}` : line;
    const result = compile(candidateSource, {
      filename: this.filename,
    });

    if (result.diagnostics.length > 0) {
      for (const diagnostic of result.diagnostics) {
        write(this.io.stderr, `${formatDiagnostic(diagnostic)}\n`);
      }
      return { exit: false, ok: false };
    }

    const candidateExecutable = stripGeneratedWrapper(result.js);
    let chunk;

    try {
      chunk = newExecutableChunk(this.executable, candidateExecutable);
    } catch (error) {
      write(this.io.stderr, `Runtime Error:\n${error.message}\n`);
      return { exit: false, ok: false };
    }

    try {
      if (chunk) {
        const newStatements = (result.ast?.body || []).slice(this.statementCount);
        const topLevelAwait = newStatements.some((statement) =>
          containsTopLevelAwait(statement)
        );
        await runScriptChunk(
          chunk,
          this.context,
          this.filename,
          topLevelAwait
        );
      }

      this.source = candidateSource;
      this.executable = candidateExecutable;
      this.statementCount = result.ast?.body?.length || this.statementCount;
      return { exit: false, ok: true };
    } catch (error) {
      write(this.io.stderr, `Runtime Error:\n${error?.message || String(error)}\n`);
      return { exit: false, ok: false };
    }
  }
}

export async function runRepl(io = {
  input: stdin,
  stdout,
  stderr,
}) {
  const input = io.input || stdin;
  const output = io.stdout || stdout;
  const errorOutput = io.stderr || stderr;
  const session = new ReplSession({
    io: {
      stdout: output,
      stderr: errorOutput,
    },
  });

  write(output, `BN Script REPL v${VERSION}\n`);
  write(output, "Type .help for commands\n");
  write(output, "Type .exit to quit\n\n");

  const rl = createInterface({
    input,
    output,
    terminal: Boolean(output.isTTY),
  });

  try {
    rl.setPrompt("> ");
    rl.prompt();

    for await (const line of rl) {
      const result = await session.handleLine(line);
      if (result.exit) {
        break;
      }
      rl.prompt();
    }
  } catch (error) {
    if (error?.code !== "ERR_USE_AFTER_CLOSE") {
      write(errorOutput, `Runtime Error:\n${error?.message || String(error)}\n`);
      return 1;
    }
  } finally {
    rl.close();
  }

  return 0;
}
